---
title: "loongraph"
author: "Kevin O'Brien"
date: "25 December 2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(loon)
```

loonGrob_layoutType A generic function used to distinguish whether only the locations of
plots will be used to arrange them in a grob, or whether all 

#### Arguments 

* to '``gridExtra::arrangeGrob()``' will be used.

#### Description 

A generic function used to distinguish whether only the locations of plots will be used to arrange
them in a grob, or whether all arguments  to '``gridExtra::arrangeGrob()``' will be used.

#### Usage
<pre><code>
loonGrob_layoutType(target)
</code></pre>

#### Arguments 

* target the (compound) loon plot to be laid out.

#### Value
either the string "locations" (the default) or the string "arrangeGrobArgs". If "locations", then
the generic function 'l_getLocations()' will be called and only the location arguments 
 of 'gridExtra::
arrangeGrob()' used (i.e. a subset of 'c("ncol", "nrow", "layout_matrix", "heights", "widths")').
The grobs to be laid out are constructed using the generic function 'l_getPlots()'.
