```{r include=FALSE, echo=FALSE}
library(knitr)
library(broom)
library(magrittr)
library(quickReg)
```

Build Regression Models Quickly and Display the Results Using 'ggplot2'


### Description 
A set of functions to extract results from regression models and plot the effect size using 'ggplot2' seamlessly. While 'broom' is useful to convert statistical analysis objects into tidy data frames, 'coefplot' is adept at showing multivariate regression results. With specific outcome, this package could build regression models automatically, extract results into a data frame and provide a quicker way to summarize models' statistical findings using 'ggplot2'.

* Depends R (>= 3.0.0)
* Imports ggplot2 (>= 2.0.0), rlang (>= 0.1.2), survival, psych, utils, stats, nortest, dplyr
* Suggests ggthemes, knitr, rmarkdown, testthat
* License GPL-2
* LazyData true
* RoxygenNote 6.0.1
* VignetteBuilder knitr
* NeedsCompilation no
* Author Xikun Han [aut, cre]
* Maintainer Xikun Han <hanxikun2014@163.com>
* Repository CRAN
* Date/Publication 2017-09-28 06:41:12 UTC
