Package ‘dygraphs’
July 12, 2018
Type Package
Title Interface to 'Dygraphs' Interactive Time Series Charting Library
Version 1.1.1.6
URL https://github.com/rstudio/dygraphs
BugReports https://github.com/rstudio/dygraphs/issues

#### Description
 An R interface to the 'dygraphs' JavaScript charting library
(a copy of which is included in the package). Provides rich facilities
for charting time-series data in R, including highly configurable
series- and axis-display and interactive features like zoom/pan and
series/point highlighting.
License MIT + file LICENSE
Depends R (>= 3.0)
Imports magrittr, htmlwidgets (>= 0.6), htmltools (>= 0.3.5), zoo (>=
1.7-10), xts (>= 0.9-7)
Suggests testthat
Enhances rmarkdown (>= 0.3.3), shiny (>= 0.10.2.1)
RoxygenNote 6.0.1
NeedsCompilation no
Author Dan Vanderkam [aut, cph] (dygraphs library in htmlwidgets/lib,
http://dygraphs.com/),
Petr Shevtsov [cre, cph],
JJ Allaire [aut],
RStudio [cph],
Jonathan Owen [aut, cph],
Daniel Gromer [aut, cph],
Benoit Thieurmel [aut, cph],
Kent Laukhuf [ctb],
jQuery Foundation [cph] (jQuery library),
jQuery contributors [ctb, cph] (jQuery library; authors listed in
inst/htmlwidgets/lib/jquery/AUTHORS.txt)
Maintainer Petr Shevtsov <petr.shevtsov@gmail.com>
1
2 dyAnnotation
Repository CRAN
Date/Publication 2018-07-11 22:00:03 UTC
R topics documented:
dyAnnotation . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . 2
dyAxis . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . 4
dyCallbacks . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . 6
dyCandlestick . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . 7
dyCrosshair . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . 10
dyCSS . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . 11
dyDataHandler . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . 12
dyDependency . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . 12
dyEvent . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . 13
dygraph . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . 14
dygraph-shiny . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . 15
dygraphs-exports . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . 15
dyGroup . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . 16
dyHighlight . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . 18
dyLegend . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . 19
dyLimit . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . 20
dyOptions . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . 21
dyPlotter . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . 25
dyPlugin . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . 25
dyRangeSelector . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . 26
dyRebase . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . 27
dyRibbon . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . 28
dyRoller . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . 29
dySeries . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . 30
dySeriesData . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . 31
dyShading . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . 32
dyUnzoom . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . 33
Index 34


