
grouped_glance
Model summary output from grouped analysis of any function that has
data argument in its function call.

#### Description

Model summary output from grouped analysis of any function that has data argument in its function
call.

#### Usage

grouped_glance(data, grouping.vars, ..f, ...)

#### Arguments

data Dataframe (or tibble) from which variables are to be taken.
grouping.vars Grouping variables.
..f A function, or function name as a string.
... 
#### Arguments
 to function.
These dots support tidy-dots features.
Methods
No methods found in currently loaded packages.
Author(s)
Indrajeet Patil

#### Examples
```{r}
set.seed(123)
# to speed up computation, let's use only 50% of the data
# linear model
broomExtra::grouped_glance(
data = dplyr::sample_frac(tbl = ggplot2::diamonds, size = 0.5),
grouping.vars = c(cut, color),
formula = price ~ carat - 1,
..f = stats::lm,
na.action = na.omit
)
# linear mixed effects model
broomExtra::grouped_glance(
data = dplyr::sample_frac(tbl = ggplot2::diamonds, size = 0.5),
grouping.vars = cut,
..f = lme4::lmer,6
grouped_tidy
)
formula = price ~ carat + (carat | color) - 1,
control = lme4::lmerControl(optimizer = "bobyqa")
