grouped_tidy
Tidy output from grouped analysis of any function that has data argu-
ment in its function call.

#### Description

Tidy output from grouped analysis of any function that has data argument in its function call.

#### Usage

grouped_tidy(data, grouping.vars, ..f, ..., tidy.args = list())

#### Arguments

data Dataframe (or tibble) from which variables are to be taken.
grouping.vars Grouping variables.
..f A function, or function name as a string.
... 
#### Arguments
 to function.
These dots support tidy-dots features.
tidy.args A list of arguments to be used in the relevant S3 method.
Value
A tibble::tibble() with information about model components.
Methods
No methods found in currently loaded packages.
Author(s)
Indrajeet Patil

#### Examples
```{r}
set.seed(123)
# to speed up computation, let's use only 50% of the data
# linear model
broomExtra::grouped_tidy(
data = dplyr::sample_frac(tbl = ggplot2::diamonds, size = 0.5),
grouping.vars = c(cut, color),
formula = price ~ carat - 1,
..f = stats::lm,
na.action = na.omit,
tidy.args = list(quick = TRUE)
)tidy
7
# linear mixed effects model
broomExtra::grouped_tidy(
data = dplyr::sample_frac(tbl = ggplot2::diamonds, size = 0.5),
grouping.vars = cut,
..f = lme4::lmer,
formula = price ~ carat + (carat | color) - 1,
control = lme4::lmerControl(optimizer = "bobyqa"),
tidy.args = list(conf.int = TRUE, conf.level = 0.99)
)
