f1Score F1 Score

#### Description  

Calculates the f1 score

#### Usage  
<pre><code>

f1Score(actual, predicted, cutoff = 0.5)

</code></pre>
#### Arguments

* ``actual``: A vector of the labels
* ``predicted``:  A vector of predicted values
cutoff A cutoff for the predicted values

fScore F Score

#### Description  

Calculates the F score and allows different specifications of the beta value (F0.5)

#### Usage  
<pre><code>

fScore(actual, predicted, cutoff = 0.5, beta = 1)

</code></pre>
#### Arguments

* ``actual``: A vector of the labels
* ``predicted``:  A vector of predicted values
cutoff A cutoff for the predicted values
beta the desired beta value (lower increases weight of precision over recall). Defaults
to 1
gini GINI Coefficient

#### Description  

Calculates the GINI coefficient for a binary classifcation model

#### Usage  
<pre><code>

gini(...)
## Default S3 method:
gini(actual, predicted, ...)
## S3 method for class 'glm'
gini(modelObject, ...)
## S3 method for class 'randomForest'
gini(modelObject, ...)
## S3 method for class 'glmerMod'
gini(modelObject, ...)
## S3 method for class 'gbm'
gini(modelObject, ...)
## S3 method for class 'rpart'
gini(modelObject, ...)
kappa 7

</code></pre>
#### Arguments

... additional parameters to be passed the the s3 methods
* ``actual``: A vector of the labels. Can be numeric, character, or factor
* ``predicted``:  A vector of predicted values
* ``modelObject``:  the model object. Currently supported glm, randomForest, glmerMod, gbm

#### Examples  

data(testDF)
glmModel <- glm(y ~ ., data = testDF, family="binomial")
Preds <- predict(glmModel, type = 'response')
gini(testDF$y, Preds)
# using s3 method for glm
gini(glmModel)
kappa kappa statistic

#### Description  

Calculates kappa statistic. Currently build to handle binary values in actual vector.

#### Usage  
<pre><code>

kappa(actual, predicted, cutoff = 0.5)

</code></pre>
#### Arguments

* ``actual``: A vector of the labels
* ``predicted``:  A vector of predicted values
cutoff A cutoff for the predicted values
8 logLoss



