---
title: "``ModelMetrics::plot_counts``"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(ModelMetrics)
```

Package ‘ModelMetrics’
November 3, 2018
Title Rapid Calculation of Model Metrics
Version 1.2.2
Date 2018-11-03

#### Description  
 Collection of metrics for evaluating models written in C++ using 'Rcpp'. Popular metrics
include area under the curve, log loss, root mean square error, etc.
Depends R (>= 3.2.2)
License GPL (>= 2)
Encoding UTF-8
LazyData true
LinkingTo Rcpp
Imports Rcpp, data.table
RoxygenNote 6.0.1
Suggests testthat
NeedsCompilation yes
Author Tyler Hunt [aut, cre]
Maintainer Tyler Hunt <thunt@snapfinance.com>
  Repository CRAN
Date/Publication 2018-11-03 17:00:14 UTC
R topics documented:
  auc . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . 2
brier . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . 3
ce . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . 4
confusionMatrix . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . 5
f1Score . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . 5
fScore . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . 6
gini . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . 6
kappa . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . 7
logLoss . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . 8
1
2 auc
mae . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . 9
mauc . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . 9
mcc . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . 10
mlogLoss . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . 11
mse . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . 11
msle . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . 12
npv . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . 13
ppv . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . 13
recall . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . 14
rmse . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . 15
rmsle . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . 15
testDF . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . 16
tnr . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . 17
Index 18
auc Area Under the Curve

#### Description  

Calculates the area under the curve for a binary classifcation model

#### Usage  
<pre><code>

auc(...)
## Default S3 method:
auc(actual, predicted, ...)
## S3 method for class 'glm'
auc(modelObject, ...)
## S3 method for class 'randomForest'
auc(modelObject, ...)
## S3 method for class 'glmerMod'
auc(modelObject, ...)
## S3 method for class 'gbm'
auc(modelObject, ...)
## S3 method for class 'rpart'
auc(modelObject, ...)
brier 3

</code></pre>
#### Arguments

... additional parameters to be passed the the s3 methods
* ``actual``: A vector of the labels. Can be numeric, character, or factor
* ``predicted``:  A vector of predicted values
* ``modelObject``:  the model object. Currently supported glm, randomForest, glmerMod, gbm

#### Examples  

data(testDF)
glmModel <- glm(y ~ ., data = testDF, family="binomial")
Preds <- predict(glmModel, type = 'response')
auc(testDF$y, Preds)
# using s3 method for glm
auc(glmModel)
