Package ‘prettyR’
==============

* October 23, 2018
* Version 2.2-2
* Title Pretty Descriptive Stats
* Date 2018-09-20
* Author Jim Lemon <drjimlemon@gmail.com>,
* Philippe Grosjean <phgrosjean@sciviews.org>
* Maintainer Jim Lemon <drjimlemon@gmail.com>

#### Description 
Functions for conventionally formatting descriptive stats,reshaping data frames and formatting R output as HTML.
Imports grDevices, stats, utils

* License GPL (>= 2)
* NeedsCompilation no
* Repository CRAN
* Date/Publication 2018-10-23 10:40:04 UTC

R topics documented:
add.value.labels . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . 2
AddNav . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . 3
AddNavItem . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . 4
addxtabs . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . 4
BeginNav . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . 5
brkdn . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . 6
calculate.xtab . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . 7
CreateIndexFile . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . 8
createIndxFile . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . 9
decimal.align . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . 9
delim.table . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . 10
delim.xtab . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . 12
describe . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . 14
describe.factor . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . 15
describe.logical . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . 16
describe.numeric . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . 17
EndHTML . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . 18
freq . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . 18
HTMLgraph . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . 20
htmlize . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . 20
Mode . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . 22
print.desc . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . 23
print.freq . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . 24
print.xtab . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . 25
R2html . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . 26
rep_n_stack . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . 28
skew . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . 29
StartList . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . 30
StartNav . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . 30
stretch_df . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . 31
toNA . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . 32
truncString . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . 33
valid.n . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . 34
xtab . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . 34
