---
title: "``timevis::setOptions``"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

#### Description

Update the configuration options of a timeline

#### Usage

<pre><code>

setOptions(id, options)

<code></pre>

#### Arguments

* id Timeline id or a timevis object (the output from timevis())
* options A named list containing updated configuration options to use. See the options parameter of the timevis function to see more details.

#### Examples
```{r}

timevis(
  data.frame(start = Sys.Date(), content = "Today"),
  options = list(showCurrentTime = FALSE, orientation = "top")
) %>%
  setOptions(list(editable = TRUE, showCurrentTime = TRUE))
```

```{r}
if (interactive()) {
  library(shiny)
  shinyApp(
    ui = fluidPage(
      timevisOutput("timeline"),
      actionButton("btn", "Show current time and allow items to be editable")
    ),
    server = function(input, output) {
      output$timeline <- renderTimevis(
        timevis(
          data.frame(start = Sys.Date(), content = "Today"),
          options = list(showCurrentTime = FALSE, orientation = "top")
        )
      )
      observeEvent(input$btn, {
        setOptions("timeline", list(editable = TRUE, showCurrentTime = TRUE))
      })
    }
  )
}

setSelection
```
