Package ‘geomnet’
December 8, 2016
Type Package
Title Network Visualization in the 'ggplot2' Framework
Version 0.2.0
Date 2016-11-14
Author Samantha Tyner, Heike Hofmann
Maintainer Samantha Tyner <sctyner@iastate.edu>
#### #### DescriptionNetwork visualization in the 'ggplot2' framework. Network
functionality is provided in a single 'ggplot2' layer by calling the geom 'net'.
Layouts are calculated using the 'sna' package, example networks are included.
License GPL (>= 2)
URL http://github.com/sctyner/geomnet
BugReports https://github.com/sctyner/geomnet/issues
LazyData TRUE
Depends R (>= 2.14), ggplot2 (>= 2.2.0)
Imports sna, network, dplyr, tidyr, readr, plotly
Suggests ggrepel, knitr, igraph, ggmap
RoxygenNote 5.0.1
NeedsCompilation no
Repository CRAN
Date/Publication 2016-12-08 20:38:18
R topics documented:
as.adjmat . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . 2
as.edgedf . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . 2
bikes . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . 3
blood . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . 4
email . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . 4
football . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . 5
1
2 as.edgedf
fortify.adjmat . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . 7
fortify.edgedf . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . 7
fortify.igraph . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . 8
fortify.network . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . 9
GeomCircle . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . 9
geom_net . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . 11
jtt . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . 15
lesmis . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . 16
madmen . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . 17
metro_map . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . 18
mm.directed . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . 18
protein . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . 19
soccer . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . 20
theme_elements . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . 21
theme_net . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . 21
Index 22
as.adjmat Cast matrix to an adjacency matrix
#### Description
Create and assign a new class for use of geomnet’s fortify.adjmat function.
Usage
as.adjmat(dat)
#### Arguments
dat A square adjacency matrix.
as.edgedf Cast a data frame to an edgedf
#### Description
Create and assign a new class for use of geomnet’s fortify.edgedf function.
Usage
as.edgedf(dat)
#### Arguments
dat A network edgelist of class "data.frame" for use with fortify.edgedf.
