
mm.directed A directed network of Mad Men relationships
#### Description
A list of two datasets, vertices and edges, containing information on sexual advances made in the TV show Mad Men. This data set was first compiled by Winston Chang for the package gcookbook (under the name madmen2) and was extended here to include the gender of each of the characters.

#### Usage
<pre><code>
mm.directed
</code></pre>

#### Format
A list of two data frames:
• the edges data set consists of two variables of length 87:
– Name1: Character variable with name of the character who made a sexual advance toward the character in Name2
– Name2: Character variable with name of the character receiving, not necessarily reciprocating, Name1’s advance.
• the vertices data set consists of two variables with information on 52 characters:
– label: Factor variable with name of the character
– Gender: Factor variable with gender of the character

#### References
Winston Chang (2012). gcookbook: Data for "R Graphics Cookbook". R package version 1.0.
https://CRAN.R-project.org/package=gcookbook
