---
title: "``geomerge::geomerge.assign``"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(geomerge)
```
Implements different assignment rules using SQL [Auxiliary Function]

#### Description

Implements assignment of polygon values to the target frame using different assignment rules.
For efficient performance implemented using SQL.

#### Usage
<pre><code>
geomerge.assign(polygon_input,target,assignment,population.data,optional.inputs,silent)
</code></pre>

#### Arguments
* ``polygon_input``: input SpatialPolygonsDataFrame parsed from geomerge main function.
* ``target``: SpatialPolygonsDataFrame representing desired units of analysis. See Details of geomerge.
* ``assignment``: identification of either population- or area-weighting assignment rules when handling SpatialPolygonsDataFrame joins to target. 
Default = "``max(area)``". See Details in geomerge.
* ``population.data``: specifies data used for weighting if a population-based assignment rule is selected. See Details in geomerge.
* ``optional.inputs``: Any optional inputs compatible with the extract function in raster.
* ``silent``: Boolean switch to suppress any (non-critical) warnings and messages. Default = FALSE.

#### Details
For details on different input parameters, please refer to the detailed documentation in geomerge.

#### Value
Returns an object of class data.frame that contains the column from input, after proper assignment, that is to be added to target@data.

#### Author(s)
Karsten Donnay and Andrew M. Linke.

#### References
Andrew M. Linke, Karsten Donnay. (2017). "Scale Variability Misclassification: The Impact of Spatial Resolution on Effect Estimates in the Geographic Analysis of Foreign Aid and Conflict."
Paper presented at the International Studies Association Annual Meeting, February 22-25 2017, Baltimore.

#### See Also
geomerge-package, geomerge, generateGrid
