

plot.geomerge Plot function for objects of class ’geomerge’.
#### Description
Overloads the default plot for objects of class ’geomerge’.
#### Usage
## S3 method for class 'geomerge'
plot(x, ...)
#### Arguments
x object of class geomerge.
... further optional #### Arguments.
Details
Returns a series of maps that visualizes numeric variables produced by geomerge. It returns a map
for each unique numeric variable including first order spatially and temporally lagged values if
spat.lag=TRUE and time.lag=TRUE when running geomerge. For spatial panels, the function by
default returns values for the last period.
Five optional #### Arguments that are specific to this plotting function can be provided. The first is
period, a numeric input that allows to specify a specific period to be plotted. inputs must be a
sequence of character strings specifying select variables to be plotted only. These have to have been
merged (with the same name) in geomerge. time.lag and spat.lag override the boolean values
parsed automatically from the result of geomerge. They are mainly meant to switch off plotting of
spatial and temporal lags as they are ignored if these lags were not generated in the first place. The
last argument is ncol, a numeric input, which allows to specify the width of the panel of plotted
maps. By default, always 2 maps are shown side-by-side.
Note
plot for objects of class ’geomerge’ relies in many core aspects of its functionality on ggplot2. If
the target SpatialPolygonsDataFrame is very large it may reach or exceed the limits of what the
plotting functionality from ggplot2 can handle and plot may be very slow or even stall.
Author(s)
Karsten Donnay and Andrew M. Linke.
References
Andrew M. Linke, Karsten Donnay. (2017). "Scale Variability Misclassification: The Impact of
Spatial Resolution on Effect Estimates in the Geographic Analysis of Foreign Aid and Conflict."
Paper presented at the International Studies Association Annual Meeting, February 22-25 2017,
Baltimore.
16 print.geomerge
See Also
geomerge
